# -*- mode: ruby -*-
# vi:set ft=ruby sw=2 ts=2 sts=2:

# Define the number of master and worker nodes
# If this number is changed, remember to update setup-hosts.sh script with the new hosts IP details in /etc/hosts of each VM.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 2

IP_NW = "192.168.5."
MASTER_IP_START_RANGE = 10
WORKER_IP_START_RANGE = 20

  Vagrant.configure("2") do |config|  
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false
  
# Provision Master Nodes
  (1..NUM_MASTER_NODE).each do |i|
      config.vm.define "master-#{i}" do |node|
        # Name shown in the GUI
        node.vm.provider "virtualbox" do |vb|
            vb.name = "master"
            vb.memory = 2048
            vb.cpus = 2
        end
        node.vm.hostname = "master"
        node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START_RANGE + i}"
        node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
        node.vm.provision "setup-hosts", :type => "shell", :path => "scripts/setup-hosts.sh"
        node.vm.provision "setup-dns", type: "shell", :path => "scripts/update-dns.sh"
        node.vm.provision "file", source: "./scripts/cert_verify.sh", destination: "$HOME/"
		node.vm.provision "password-change", type: "shell", :path => "scripts/password-change.sh"
		node.vm.provision "install-docker", type: "shell", :path => "scripts/install-docker.sh"
		node.vm.provision "setup-cluster", type: "shell", :path => "scripts/setup-cluster.sh"

      end
  end

  # Provision Worker Nodes
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "worker-#{i}" do |node|
        node.vm.provider "virtualbox" do |vb|
            vb.name = "worker-#{i}"
            vb.memory = 512
            vb.cpus = 1
        end
        node.vm.hostname = "worker-#{i}"
        node.vm.network :private_network, ip: IP_NW + "#{WORKER_IP_START_RANGE + i}"
		node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
        node.vm.provision "setup-hosts", :type => "shell", :path => "scripts/setup-hosts.sh"
        node.vm.provision "setup-dns", type: "shell", :path => "scripts/update-dns.sh"
		node.vm.provision "file", source: "./scripts/cert_verify.sh", destination: "$HOME/"
		node.vm.provision "password-change", type: "shell", :path => "scripts/password-change.sh"
        node.vm.provision "install-docker", type: "shell", :path => "scripts/install-docker.sh"
		node.vm.provision "setup-cluster", type: "shell", :path => "scripts/join-node-to-cluster.sh"
        
    end
  end
end